name: Deploy EC2

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
  EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
      
      - name: SSH into remote server and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@$EC2_IP "\
            ./github_action.sh"
